### ISSUE TITLE
Is ember-burger-menu abandoned?

### ISSUE THREAD

**Issue by tythewebguy** [adopted-ember-addons/ember-burger-menu#148]
Things broke in `ember-burger-menu` when I recently upgraded to Ember 3.27 in preparation for the 3.28LTE and future 4.0 version. It looks like things have been quiet around here and development stopped on Ember 3.3. 

Is this add-on now abandoned?

**Comment by rwwagner90** [comment]
@tythewebguy yeah, it is abandoned. @offirgolan want to transfer this one to adopted-ember-addons as well?

**Comment by rwwagner90** [comment]
@tythewebguy Got it transferred and I am currently updating all the things!
