### ISSUE TITLE
Problems with acceptance testing

### ISSUE THREAD

**Issue by juanazam** [adopted-ember-addons/ember-burger-menu#91]
Hi,

First of all, thanks for all the hard work on this great addon, it works great!

I'm having issues with opening the menu while writing acceptance tests. I tried pausing the test and opening the menu manually but it refuses to work on the acceptance test environment.

Maybe I'm missing something, but it seems it just doesn't work.

**Comment by offirgolan** [comment]
@juanazam I'm not sure. Can you post some screenshots and some code samples?

**Comment by juanazam** [comment]
@offirgolan The only problem is that the menu transformations are not displayed. The menu is never displayed as open when the test is running. You can do assertions on its content but visually it's not working. I guess this is not a big deal but it is a bit missleading.

**Comment by offirgolan** [comment]
Huh thats weird. It could be some viewport CSS issues. My suggestion would be to use `pauseTest()` and see what the width / height of the parent containers are for the ember-burger-menu element. If that doesnt work, let me know and I'll try to figure out whats going on.

**Comment by juanazam** [comment]
@offirgolan It seems that the scaling done to show the app within the testing container is messing up with `ember-burger-menu`'s CSS. I already used `pauseTest()` but I was not able to figure out why it's not being displayed as it should.

**Comment by offirgolan** [comment]
Ah damn. Okay I'll investigate this further and see if I can figure something out.
